version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apiDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - app_network

  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DESIGN: dracula  
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "8081:8080"

volumes:
  postgres_data:

networks:
  app_network: