name: connect_card
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.0
  http: ^0.13.3
  crypto: ^3.0.6
  flutter_dotenv: ^5.1.0
  icons_plus: 5.0.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env
